spring.application.name=merchant-service
server.port=8082

spring.datasource.url=YOUR_ORACLE_JDBC_URL
spring.datasource.username=YOUR_ORACLE_USERNAME
spring.datasource.password=YOUR_ORACLE_PASSWORD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret-base64=YOUR_SHARED_BASE64_JWT_SECRET 
server.error.include-stacktrace=never